name: mapita_del_caribe
description: "Aplicación diseñada para actuar como mapa de la universidad del caribe"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  panorama_viewer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/C11_2.jpg
    - lib/assets/Biblio.jpg
    - lib/assets/Practicas.jpg
    - lib/assets/Tallercocina.jpg
    - lib/assets/Vinculacion.jpg
    - lib/assets/EdificioF.jpg
    - lib/assets/Patronato.jpg
